[package]
name = "alice"
version = "0.1.0"
edition = "2021"

[dependencies]
rabbitmq-stream-client = "*"
tokio = { version = "1", features = ["full"] }
futures = "0.3.0"
tracing = "0.1"
tracing-subscriber = "0.3.16"
